### ISSUE TITLE
不能解决重复问题

### ISSUE THREAD

**Issue by yuxueliang** [lun3322/SnowflakeId#2]
测试代码：
static void Main(string[] args)
        {
            var blockingCollection = new BlockingCollection<long>();
            List<Task> tasks = new List<Task>();
            for (int i = 0; i < 100; i++)
            {
               var task =  Task.Run(()=>{

                    for (int j = 0; j < 10000; j++)
                    {

                        blockingCollection.Add(new SnowflakeIdWorker(1,1).NextId());
                    }
                });

                tasks.Add(task);
            }

            Task.WaitAll(tasks.ToArray());

            Console.WriteLine(blockingCollection.Distinct().Count());

            Console.ReadKey();
           
        }

**Comment by lun3322** [comment]
结果对

你可能是因为每次都new一个worker出现的问题
```
blockingCollection.Add(new SnowflakeIdWorker(1,1).NextId());
```

**Comment by yuxueliang** [comment]
> 结果对
> 
> 你可能是因为每次都new一个worker出现的问题
> 
> ```
> blockingCollection.Add(new SnowflakeIdWorker(1,1).NextId());
> ```

我执行我复制的那段代码是不对的，多线程肯定是每次都new一个worker的

**Comment by lun3322** [comment]
[代码](https://github.com/lun3322/SnowflakeId/blob/b9c543847a4fcd3b276c9027c43d65fe27033e89/SnowflakeId.Core/SnowflakeIdWorker.cs#L84)

workerId和datacenterId,每个线程设置成不同的id
